/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    ButtonItem: typeof import('./src/components/Button/ButtonItem.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElFormVInput: typeof import('element-plus/es')['ElFormVInput']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/Icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/Icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/Icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/Icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/Icons/IconTooling.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    InputItem: typeof import('./src/components/Input/InputItem.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VArrowForWard: typeof import('./src/components/Icons/VArrowForWard.vue')['default']
    VButton: typeof import('./src/components/Button/VButton.vue')['default']
    VInput: typeof import('./src/components/Input/VInput.vue')['default']
    VLogin: typeof import('./src/components/VLogin.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
