/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/Icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/Icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/Icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/Icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/Icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VArrowForWard: typeof import('./src/components/Icons/VArrowForWard.vue')['default']
    VButton: typeof import('./src/components/Button/VButton.vue')['default']
    VInput: typeof import('./src/components/Input/VInput.vue')['default']
  }
}
